services:
  mysql:
    image: mysql:latest
    container_name: cgvMysql
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: cgvDB       # ✅ 이 한 줄이 DB 생성
      MYSQL_USER: admin
      MYSQL_PASSWORD: test123
    ports:
      - "3307:3306"
    volumes:
      - cgv_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - redis_data:/data

  kafka-1:
    container_name: kafka-1
    image: confluentinc/cp-kafka:7.5.3
    platform: linux/amd64
    ports:
      - "9092:9092"  # 내부 포트 9092 외부 포트 9092
      - "9093:9093"  # 외부 포트 9093 추가
    volumes:
      - ./data/kafka-data/kafka-1:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://localhost:9093  # 외부에서 접근하는 포트 9093
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,CONTROLLER://:29093,EXTERNAL://0.0.0.0:9093  # EXTERNAL 리스너 포트 9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1



  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    platform: linux/amd64
    ports:
      - "8082:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092
    depends_on:
      - kafka-1

  controller:
    image: ngrinder/controller:3.5.5-p1
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ngrinder_data:/opt/ngrinder-controller
  agent:
    image: ngrinder/agent:3.5.5-p1
    links:
      - controller

volumes:
  cgv_data:
  redis_data:
  ngrinder_data: