services:
  mysql:
    image: mysql:latest
    container_name: cgvMysql
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: cgvDB       # ✅ 이 한 줄이 DB 생성
      MYSQL_USER: admin
      MYSQL_PASSWORD: test123
    ports:
      - "3307:3306"
    volumes:
      - cgv_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - redis_data:/data


volumes:
  cgv_data:
  redis_data: